name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "862e65a1e015e9609b29ea256cebac2a2bb73f911cfb5c38e2007d4c65421c42"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.41"
