name = "getchoos-modpack"
author = "getchoo"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b91559c2fb2c19477eda6bf3d7ede97343cacaaba79b79f8725e40dd7f28f57"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
