name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c37e9f40c9d5a38fffed2c15e145b8e3769c3ff0c61f1108d0195e08de0f817d"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
