name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69992d5f265e18290008f91d36b208d5d22c38c0e45f5c543e1778dea4c25adb"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
