name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfb7e1879f474e1d732fef60031087e887180d9b48d620d159f25b38edc927af"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
