name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1000b79fb93a37fc69efaf5e642029c3c8919ae736986d7311ec0f4cfe69c14a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
