name = "getchoos-modpack"
author = "getchoo"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fccb9cc6a1fd5bfb0c3dcdaec75174232e63a8690924b90eeb09dfaa953c10f5"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
