name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1febe7e6a0e7d3191ac1f2f859b96fe07b2cf4ac5012a626901b132858ae6144"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
