name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe41aabbf1ec3fb7455f9dca6b2cded7e9089627f9e691caaf73ad78f3a69fc3"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
