name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab583eb763c6e67df356c047019def19275cfabc08a1c825a71055db539a1b44"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
