name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c878651a4825d2cf63d8488dc9b9d48460deab054602674b8f107845981299a"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
