name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7349b986f9bb454e092f3c847e75a5cfa81e07302aabaea124dc40a05542561e"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
