name = "getchoos-modpack"
author = "getchoo"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ab526a94d8cad5efb2758bd4dd4155511229412b007d204ca82dba08de65ba"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
