name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "936cd3b3b74ed88b840ebd5cc4a74894a29e7dca4de91a30138d17e7955a1c8c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
