name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49c3931ff318295c0ab1b247c9e9d47a541e81119a4ea46e3f30580fdc46c2f2"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
