name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63798af8b22d671dc5dd621c064cd8e15ff3d6230a6d88322ca688888d29fe2b"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
