name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0353348581ce707a88b635c5eae125166ae370fc6bbf686232f7d87271c71ea"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
