name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3b6a94b522455c92b9328d90144bad47f665b7a2c547178c364b2bdb9f2e279"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
