name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c4d562bbf5900cdb95de7cb520bac439aa8f1dfba4b54e03220ce96600f4c82"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
