name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8123b8833361a2e734706828b1f8ae0a819b14d176ef26f23153ae1490f7ec9b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
