name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebc1aff72f8bb725a909f025e9b415aadf7485c1c001237de2e906081b458d24"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
