name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f63a594c82761ac34f2eadd8ac8bd4707cff11e878c0c342ded0c882f928c783"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
