name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1587317a6784bf3934ddeec5e5f00441caab884f77bec04cac15c38e9b5f9306"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
