name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf34a6928511c0db72c683c8cd912bb55f6ad1402e9bdfa315ff90ecf696766"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
