name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "076e63fedcd47378bdc205f0c0980cd02497fe72a517f24ac3fab1534b5b9197"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
