name = "server-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd6e8e4b13a0586b144a36e7b04fa3436815265be834aefdbfa7ecab01bd1614"

[versions]
minecraft = "1.19.3"
quilt = "0.18.10"
