name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c6dae98122a44238142fa05ff30a592f885c381b49c2116caf02de8094dbdb8"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
