name = "getchoos-modpack"
author = "getchoo"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d28d3c02fa3e65c58cf30f65765905601472f21d51aa0d3afc0fc523b50692c"

[versions]
minecraft = "1.19.4"
quilt = "0.19.1"
