name = "getchoos-modpack"
author = "getchoo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57b8f1f0442f5da0fe400944f0497aeb9076f3da466434b61256eeac47e7d9c0"

[versions]
minecraft = "1.19.3"
quilt = "0.18.7"
