name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75ac8f93c9a0413a56bb0bcdb18c27696589fd2fcb015e20f55278797047df0e"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
