name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c1fce7db5388aa07168015d53ecd137fe4445a81d31e44a74b1362b9c16e40a"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
