name = "getchoos-modpack"
author = "getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "084a19322c414640de6aa03f8a59ba93844fd5ec18e9659949642606877d7e19"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
